### PR TITLE
fix(g-canvas): clip animation should be effective

### LINKED ISSUE #218: [4.0] 支持 shape 的 clip 动画
G2 的折线图的动画采用的是给 shape 设置剪切区域的方案，代码如下：

```js
  const clipCfg = getCoordinateClipCfg(coordinate); // 获取剪切区域图形配置
  const endState = clipCfg.endState;
  // 为 shape 设置剪切区域
  const clipShape = shape.setClip(clipCfg);

  // 对剪切图形做动画
  const { easing, duration, delay } = animateCfg;
  clipShape.animate(endState, duration, easing, () => {
    if (shape && !shape.get('destroyed')) {
      shape.set('clipShape', null); // 移除剪切图形
    }
  }, delay);
```

期望：
* 目前上述代码并没有达到预期，希望能够
* ` shape.setClip(clipCfg)` 应该返回创建的 clipShape
*  用户调用 `shape.set('clipShape', null)` ，默认应该将 clipShape 销毁

### PR DESCRIPTION
**Pull request by dengfuping**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Performance improvement
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

- Close #218.

### 💡 Background and solution

- `hasChanged` should be updated after `clip` is drawn:
```diff
_applyClip(context, clip: ShapeBase) {
  if (clip) {
    clip.createPath(context);
    context.clip();
+   clip._afterDraw(); // clip 绘制完成后，需要缓存包围盒以及清除标记
  }
}
```

### 📝 Changelog

| Language     | Changelog |
| ------------ | --------- |
| 🇺🇸 English | 🐞 [g-canvas] Fix that clip animation is not effective. #218 |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复裁剪动画不生效的问题。#218 |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: packages/g-base/src/abstract/element.ts [hunk 1]
```diff
@@ -112,6 +112,18 @@ abstract class Element extends Base implements IElement {
     };
   }
 
+  // 覆盖基类中的 set 方法
+  set(name, value) {
```
Comment (dxq613) [inline packages/g-base/src/abstract/element.ts]: 去除复写 set
