### PR TITLE
fix(g-canvas): stroke attr should be working for Text

### LINKED ISSUE #266: [4.0] stroke attr is not working for Text of g-canvas
- [x] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/g-40-canvas-text-stroke-hd4yr)

### Steps to reproduce
- See the demo.

### What is expected?
- `stroke` attr should be working for Text of g-canvas.

### What is actually happening?
- `stroke` attr is not working for Text of g-canvas.

| Environment | Info |
|---|---|
| g-canvas | 0.1.0-beta.11 |
| System | Mac OS |
| Browser | Google Chrome 77.0.3865.90 |

### PR DESCRIPTION
**Pull request by dengfuping**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Performance improvement
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

- Close #266.

### 📝 Changelog

| Language     | Changelog |
| ------------ | --------- |
| 🇺🇸 English | 🐞 [g-canvas] Fix that `stroke` attr is not working for Text. #266         |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复 Text 的 `stroke` 属性不生效的问题。#266          |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: packages/g-canvas/src/shape/text.ts [hunk 1]
```diff
@@ -210,7 +210,11 @@ class Text extends ShapeBase {
       this._drawTextArr(context, textArr, isFill);
     } else {
       const text = attrs.text;
-      context.fillText(text, x, y);
```
Comment (dxq613) [inline packages/g-canvas/src/shape/text.ts]: fill 和 stroke 同时使用时怎么办？

Comment (dengfuping) [reply packages/g-canvas/src/shape/text.ts]: - 如果同时设置，`fill()` 和 `stroke()` 方法都会调用的，即会调用两次 `_drawText()` 方法。已经测试过两个属性都设置的场景了。

Comment (dengfuping) [reply packages/g-canvas/src/shape/text.ts]: - 不过这里的逻辑可以优化下，现在同时设置 `fill` 和 `stroke` 可能会渲染两次。
