### PR TITLE
fix(g-canvas): make non-array value compatible with lineDash

### LINKED ISSUE #206: G  4.0 lineDash 设置了后，无法取消
- [x] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/g-canvas-linedash-1zuzx)

[https://github.com/antvis/g/blob/4.x/packages/g-canvas/src/util/draw.ts#L22](https://github.com/antvis/g/blob/4.x/packages/g-canvas/src/util/draw.ts#L22)

### Steps to reproduce
shape.attr('lineDash', [2, 2]); 后 调用 shape.attr('lineDash', null);  报错

### What is expected?
调用 shape.attr('lineDash', null);  不再出现 lineDash 效果

### What is actually happening?
报错

| Environment | Info |
|---|---|
| g | 4.0 |
| System | 任意 |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by dengfuping**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Performance improvement
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

- Close #206.

### 💡 Background and solution

- Non-array value is equivalent to empty array for `lineDash` attribute.

### 📝 Changelog

| Language     | Changelog |
| ------------ | --------- |
| 🇺🇸 English | 🐞 [g-canvas] Fix that non-array value is not compatible with lineDash. #206 |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复 `lineDash` 为非数组值时页面报错的问题。 #206 |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: packages/g-canvas/src/util/draw.ts [hunk 1]
```diff
@@ -20,8 +21,8 @@ export function applyAttrsToContext(context: CanvasRenderingContext2D, element:
       // 设置矩阵
       context.transform(v[0], v[1], v[3], v[4], v[6], v[7]);
     } else if (name === 'lineDash' && context.setLineDash) {
-      // 不再考虑支持字符串的形式
-      context.setLineDash(v);
+      // 设置虚线，只支持数组形式，非数组形式按照 [] 处理，即不设置任何虚线
+      context.setLineDash(isArray(v) ? v : []);
```
Comment (dxq613) [inline packages/g-canvas/src/util/draw.ts]: isArray(v) && context.setLineDash(v) 是不是更好一些，直接不调用这个方法

Comment (dengfuping) [reply packages/g-canvas/src/util/draw.ts]: - 不调用这个方法，那么就不会重置虚线效果，设置 `null` 或 `false` 就相当于不起作用，应该不太符合用户预期。

Comment (dengfuping) [reply packages/g-canvas/src/util/draw.ts]: - 由于 `shape` 绘制前后会调用 `context.save()` 和 `context.restore()` 方法，因此 `context.setLineDash(v)` 并不会影响下次绘制，非数组形式不做任何操作即可。
- 实现改为:
```js
// 设置虚线，只支持数组形式，非数组形式不做任何操作
isArray(v) && context.setLineDash(v);
```
