### PR TITLE
fix: `HTML` element bounding box calculation logic #1743

### LINKED ISSUE #1743: The bounding box information obtained by the canvas element and the html element is inconsistent
Create a **canvas element** and an **html elemen**t and make them completely overlap:

```typescript
const circle = new Circle({
  style: {
    cx: 200,
    cy: 200,
    r: 50,
    fill: 'red',
  },
});

const html = new HTML({
  style: {
    x: 150,
    y: 150,
    width: 100,
    height: 100,
    innerHTML:
      '<h1 style="width: 100px; height: 100px;">This is Title</h1>',
  },
});
```

Measure the bounding box information in three situations: 

- initial state
- camera translation
- camera zoom
 
and compare them.

image

As shown in the figure above, the bounding box information of the html element will change, while that of the canvas element (circle) will not change.

---

The inconsistency between the canvas element and the html element behavior results in some incorrect visual effects when the two are used together, such as https://github.com/antvis/G6/issues/5781

---

- `getBBox()`
  - https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement/getBBox
  - https://www.w3.org/TR/SVGTiny12/svgudom.html#svg__SVGLocatable
  - https://stackoverflow.com/questions/6179173/how-is-the-getbbox-svgrect-calculated
- `getBoundingClientRect()`
  - https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect 
  - https://drafts.csswg.org/cssom-view/#dom-element-getclientrects

### PR DESCRIPTION
**Pull request by wang1212**
Subtract the camera's transformation from the bounding box calculation logic of the `HTML` element to keep the result consistent with the native canvas element

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / Document optimization
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Performance improvement
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

- fixed #1743

### 💡 Background and solution

Detailed questions can be found #1743 .

The root cause is that the camera transformation and element transformation of G are independent, which means that if only the camera is adjusted, the transformation of the canvas element will not change.

However, the implementation of `getBoundingClientRect()` of `HTML` type elements simply calls the DOM API, because the transformation of the camera `div` element as the parent element is also included, which is inconsistent with the calculation logic of the canvas element.

Therefore, the camera transformation needs to be eliminated in the implementation of `getBoundingClientRect()` of `HTML` type elements.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  fix: subtract the camera's transformation from the bounding box calculation logic of the `HTML` element to keep the result consistent with the native canvas element (#1743)  |
| 🇨🇳 Chinese |  fix: `HTML` 元素包围盒计算逻辑中减去相机的变换，保持和原生 canvas 元素的结果一致 (#1743) |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: packages/g-lite/src/shapes/Rectangle.ts [hunk 1]
```diff
@@ -1,9 +1,87 @@
...
+   * @see https://developer.mozilla.org/en-US/docs/Web/API/DOMRect/fromRect_static
+   */
+  static fromRect(rect: RectangleLike) {
+    return new Rectangle(rect.x, rect.y, rect.width, rect.height);
+  }
+
+  /**
+   * will return a new rect instance
+   */
+  static applyTransform(rect: Rectangle, matrix: mat4) {
```
Comment (Aarebecca) [inline packages/g-lite/src/shapes/Rectangle.ts:21]: 这个放到工具方法会不会好些

Comment (wang1212) [reply packages/g-lite/src/shapes/Rectangle.ts:21]: 这个参考了其它 shape 的实现，发现大部分变换相关的都是在 class 里面直接实现的，目前用途相对单一，后续如果有其它模块的依赖，可以考虑重构一下作为工具函数实现

**Review by Aarebecca — APPROVED** [review]
