### PR TITLE
fix(g-svg): group.addShape should work when group dom is not created

### LINKED ISSUE #276: [4.0] SVG 虚拟 Group 问题死循环
G2 4.0 中使用一个虚拟 group 来做 element 的属性变更。ref https://github.com/antvis/G2/blob/6a714fa8ffe30b19866566bcb27c2a33bcdb54c8/src/geometry/element/index.ts#L82-L87

复现代码：https://riddle.alibaba-inc.com/riddles/1bd88c7a

----

同理也会报一下错误：

image

### PR DESCRIPTION
**Pull request by dengfuping**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Performance improvement
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

- Close #276 

### 💡 Background and solution

- Just create dom when `parentNode` is null.

### 📝 Changelog

| Language     | Changelog |
| ------------ | --------- |
| 🇺🇸 English | 🐞 [g-svg] Fix that group.addShape should work when group dom is not created. #276      |
| 🇨🇳 Chinese | 🐞 [g-svg] 修复当图形分组没有对应的 `el` 元素时，调用 addShape 方法导致死循环的问题。#276          |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: packages/g-svg/src/util/dom.ts [hunk 1]
```diff
@@ -21,11 +21,14 @@ export function createDom(shape: IShape) {
...
   if (parent) {
     let parentNode = parent.get('el');
-    while (!parentNode) {
-      const newParent = parent.getParent();
-      parentNode = newParent && newParent.get('el');
+    if (parentNode) {
+      parentNode.appendChild(element);
+    } else {
+      // parentNode maybe null for group
+      parentNode = (parent as IGroup).createDom();
```
Comment (dxq613) [inline packages/g-svg/src/util/dom.ts]: IGroup 好像没有定义 createDom 方法

Comment (dengfuping) [reply packages/g-svg/src/util/dom.ts]: - `g-svg` 扩展了一下暴露出来的接口:
https://github.com/antvis/g/blob/988c3c72c20bad14a0cb5ea42b2aa558a6658b97/packages/g-svg/src/interfaces.ts#L32

Comment (dxq613) [reply packages/g-svg/src/util/dom.ts]: 好吧，跟我学坏了。。。

**Comment by hustcc** [comment]
还有另外一个问题，因为没有 addCanvas 导致 canvas 为 undefined。

image

**Comment by hustcc** [comment]
> 还有另外一个问题，因为没有 addCanvas 导致 canvas 为 undefined。
> 
> image

在 legend 中使用了虚拟 group 去绘制，大概伪代码如下，就会报错：

```ts
const Ctor = group.getGroupBase();

cont g = new Ctor({});

const shape = g.addShape(...);

shape.attr('x', 100);
```

@dengfuping @dxq613

**Comment by dengfuping** [comment]
@hustcc 确实有这个问题，这个 PR 会一起解决 g-svg 的这些问题。
