### PR TITLE
fix(g-base): should emit drag event for canvas only when draggable is true

### LINKED ISSUE #380: Canvas 的 draggable 为 true 时才允许触发拖拽事件

### PR DESCRIPTION
**Pull request by dengfuping**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / Document optimization
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Performance improvement
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

- Close #380.

### 💡 Background and solution

-  `draggable: false` 时，对画布进行拖拽操作，事件响应顺序为: `mousedown -> mousemove -> mouseup -> click`;
- `draggable: true` 时，对画布进行拖拽操作，事件响应顺序为: `mousedown -> mousemove(是否触发取决于拖拽的速度和距离) -> dragstart -> drag -> dragend`;

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | 🐞 [g-base] Fix that canvas could emit drag event when `draggable` is false. #380        |
| 🇨🇳 Chinese | 🐞 [g-base] 修复当 `draggable` 为 `false` 时，canvas 能够触发 `drag` 事件的问题。#380          |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: packages/g-base/src/event/event-contoller.ts [hunk 1]
```diff
@@ -406,15 +407,24 @@ class EventController {
...
+            // 设置了 draggable 的 shape 才能触发 drag 相关的事件
             draggingShape = this.mousedownShape; // 拖动鼠标点下时的 shape
             draggingShape.set('capture', false); // 禁止继续拾取，否则无法进行 dragover,dragenter,dragleave,drop的判定
             this.draggingShape = draggingShape;
+            this.dragging = true;
+            this._emitEvent('dragstart', event, pointInfo, draggingShape);
+          } else if (!mousedownShape && canvas.get('draggable')) {
+            // 设置了 draggable 的 canvas 才能触发 drag 相关的事件
+            this.dragging = true;
+            this._emitEvent('dragstart', event, pointInfo, draggingShape);
```
Comment (dxq613) [inline packages/g-base/src/event/event-contoller.ts]: 这个地方可以直接写成 this._emitEvent('dragstart', event, pointInfo, null); 了

File: packages/g-base/src/event/event-contoller.ts [hunk 2]
```diff
@@ -406,15 +407,24 @@ class EventController {
...
+          } else {
+            this._emitMouseoverEvents(event, pointInfo, preShape, shape);
+            this._emitEvent('mousemove', event, pointInfo, shape);
           }
-          this.dragging = true;
+
           // 清理按下鼠标时缓存的值
           this.mousedownShape = null;
```
Comment (dxq613) [inline packages/g-base/src/event/event-contoller.ts]: 这两个变量清空，感觉应该在 drag 的时候，如果非 drag 的第三个条件 （else) 的话，哪怕没有拖拽， click 也没法触发了，也不是什么问题，但你需要搞清楚是否是你的意图。

Comment (dengfuping) [reply packages/g-base/src/event/event-contoller.ts]: - 对于 drag，清空这两个变量是为了保证 mousedown 时只触发一次 dragstart 事件；而对于非 drag，清空这两个变量，那下次 mousemove 就会执行另外一个分支逻辑。虽然从结果上看是一样的，但还是有区别(`mousedown + mousemove VS mousemove`)，所以非 drag 不清空变量更合理。
```js
if (mousedownPoint) {
    // 非 drag 时没有清空变量
} else {
    // 非 drag 时清空了变量
}
```

File: packages/g-base/src/event/event-contoller.ts (hunk 1 above)
Comment (dengfuping) [reply packages/g-base/src/event/event-contoller.ts]: - 已修复
